apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: Cluster
metadata:
  name: release-i-0583a-2c27bc6
  namespace: default
spec:
  bundlesRef: null
  clusterNetwork:
    cniConfig:
      cilium: {}
    pods:
      cidrBlocks:
      - 192.168.0.0/16
    services:
      cidrBlocks:
      - 10.96.0.0/12
  controlPlaneConfiguration:
    count: 1
  datacenterRef:
    kind: DockerDatacenterConfig
    name: release-i-0583a-2c27bc6
  eksaVersion: v0.0.0-dev-release-0.17+build.86
  externalEtcdConfiguration:
    count: 1
  gitOpsRef:
    kind: FluxConfig
    name: eksa-test
  kubernetesVersion: "1.27"
  managementCluster:
    name: release-i-0583a-2c27bc6
  workerNodeGroupConfigurations:
  - count: 1
    name: md-0

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: DockerDatacenterConfig
metadata:
  name: release-i-0583a-2c27bc6
  namespace: default
spec: {}

---
apiVersion: anywhere.eks.amazonaws.com/v1alpha1
kind: FluxConfig
metadata:
  name: eksa-test
  namespace: default
spec:
  branch: aws-eks-anywhere-test-docker-release-0-17-2f533f6a-143d-4a95-a970-8dec7abde630-3
  clusterConfigPath: aws-eks-anywhere-test-docker-release-0-17-2f533f6a-143d-4a95-a970-8dec7abde630-3
  git:
    repositoryUrl: ssh://git@github.com/that-jetpack-guy/aws-eks-anywhere-test-docker-release-0-17-2f533f6a-143d-4a95-a970-8dec7abde630-3.git
  systemNamespace: default

---
